Added possibility to use an existing config file for recursor or auth…
pschiffe/docker-pdns pull request #135
Opened 2024-05-03 11:55 UTC by murphy83

Idea to have the option to use an already existing (eg. externally generated) config file for recursor or authorative power-dns-mysql).
The behavior is controlled by setting the environment variable USE_EXISTING_CONFIG_FILE to "true". Disabled by default.

2024-05-03 15:05 UTC, pschiffe commented
Hello @murphy83 , thank you for your contribution. I'm OK with this change, however, could you update also the `pdns-pgsql` image, so both images (`pdns-pgsql` and `pdns-mysql`) are equal feature-wise? Thank you.

2024-05-03 15:18 UTC, murphy83 commented
I was thinking about this idea already, however I am still not 100% sure  about the path to follow, as usually refrain from "just duplicating code". So I am a bit tempted to use something like a functions-file to include for the parts that are valid for both Postgres and MySQL/MariaDB.
Let me know what you think fits better in your opinion.

2024-05-03 16:00 UTC, pschiffe commented
Feel free to do what you prefer. I've kept it separate as it's really not that much code, it's fairly simple and not updated that often.

2024-05-03 16:03 UTC, murphy83 commented
OK I think I will set to work on this in the evening.

2024-05-05 13:25 UTC, pschiffe requested changes

2024-05-05 13:25 UTC, pschiffe commented on pdns-mysql/docker-entrypoint.sh
> +function initSuperslave {
this function is never called in both (mysql & pgsql)

2024-05-05 13:25 UTC, pschiffe commented on pdns-pgsql/docker-entrypoint.sh
> +  # Configure mysql env vars
copy paste error

2024-05-05 13:25 UTC, pschiffe commented on pdns-pgsql/docker-entrypoint.sh
> +function generateAndInstallConfigFileFromEnvironment {
fn never called in this variant

2024-05-06 06:47 UTC, murphy83 commented
Indeed ... this function was defined but never called ...

2024-05-06 15:12 UTC, pschiffe approved these changes

2024-05-06 15:13 UTC, merged